version:
  "3.9"
  # This is a simple docker container for running a postgres database in the local dev environment.
services:
  db:
    image: postgres:latest
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: ${DEV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DEV_POSTGRES_DB}
    ports:
      - "${DEV_POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "michael.poulgrain@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "testPassword"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  postgres_data:
  pgadmin_data:
