name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    if: github.event.action != 'closed'
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Test
        id: test
        run: pnpm run test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Deploy
        run: pnpm sst deploy --stage pr-${{ github.event.number }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NEXT_PUBLIC_HIGHLIGHT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_HIGHLIGHT_PROJECT_ID }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Wait for deployment to finish
        run: pnpm run db migrate --stage pr-${{ github.event.number }}

  remove:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install

      - name: Remove
        run: pnpm sst remove --stage pr-${{ github.event.number }}
