name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    if: github.event.action != 'closed'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test
        continue-on-error: true

      - name: Upload log file if tests fail
        if: failure() # This condition checks if the previous step failed
        uses: actions/upload-artifact@v3
        with:
          name: sst-log.log
          path: "./.sst/log/sst.log"

      - name: Stop execution if tests fail
        if: failure()
        run: exit 1 # Explicitly fail the workflow

      - name: Deploy
        run: pnpm sst deploy --stage pr-${{ github.event.number }}

      - name: Wait for deployment to finish
        run: pnpm run db migrate --stage pr-${{ github.event.number }}

  remove:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Install dependencies
        run: pnpm install

      - name: Remove
        run: pnpm sst remove --stage pr-${{ github.event.number }}
