name: Versioning

on:
  push:
    branches:
      - main
      - ci/test

jobs:
  release:
    permissions:
      contents: write

    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        with:
          dry_run: ${{ github.ref_name == 'ci/test' }}

      - run: echo ${{ steps.semantic.outputs.new_release_version }}

      - name: Deploy
        if: steps.semantic.outputs.new_release_published == 'true'
        run: pnpm sst deploy --stage production
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NEXT_PUBLIC_HIGHLIGHT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_HIGHLIGHT_PROJECT_ID }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: Migrate Database
        if: steps.semantic.outputs.new_release_published == 'true'
        run: pnpm sst shell --stage production -- pnpm -F db db:migrate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
