name: Testing versioning

on:
  push:
    branches:
      - ci/test

jobs:
  release-test:
    permissions:
      contents: write

    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --dry-run
